export const carList = [
  {"id":"NEWCAR1",
   "photo":require('./assets/cars-clipped/29-speedster.png'),
   "year":"1929", 
   "make":"Ford", 
   "model":"Model A Speedster",
   "engine":"Highly Modified 1932 Model B 205ci Flathead 4-Cylinder",
   "horsepower":"75-90",
   "fuelDelivery":"Two Single-Barrel Carburetors", 
   "transmission":"3-Speed Manual", 
   "brakes":"Drum", 
   "color":"Black", 
   "interior":"Red Leather", 
   "production":"4,850,000 between 1928-1931", 
   "price":"$385 stock",
   "gallery":[
       require('./assets/29-speedster/1.jpg'),
       require('./assets/29-speedster/2.jpg'),
       require('./assets/29-speedster/3.jpg'),
       require('./assets/29-speedster/4.jpg'),
       require('./assets/29-speedster/5.jpg'),
       require('./assets/29-speedster/6.jpg'),
       require('./assets/29-speedster/7.jpg'),
       require('./assets/29-speedster/8.jpg'),
       require('./assets/29-speedster/9.jpg'),
       require('./assets/29-speedster/10.jpg'),
       require('./assets/429-speedster/11.jpg'),
       require('./assets/429-speedster/12.jpg'),
       require('./assets/429-speedster/13.jpg'),
       require('./assets/429-speedster/14.jpg'),
       require('./assets/429-speedster/15.jpg'),
       require('./assets/429-speedster/16.jpg'),
       require('./assets/429-speedster/17.jpg'),
       require('./assets/429-speedster/18.jpg'),
       require('./assets/429-speedster/19.jpg'),
   ],
   "story":[
      {"para_id":"1", "para":"When U.S. automobile production resumed in the fall of 1945, pre-war vehicles that survived the scrap drives of World War II became instant bargains as people rushed to buy new cars. In particular, it was not unusual to buy running Model A Fords for less than $25 and create a home-built “high-performance” car on the cheap."}, 
      {"para_id":"2", "para":"The idea of a Speedster was nothing new as, for years, early speed demons had been building street cars that copied the looks and performance of early open wheel racers. Many were based on the Ford Model T, where one would lighten the car by removing the fenders and most of the body, then modify the engine for more horsepower. The end result was a dangerously exciting vehicle that could perform way beyond its original capabilities."},
      {"para_id":"3", "para":"The Ford Model A was a much better starting point for a Speedster. It had a stiffer frame, which could handle all sorts of engine conversions, and four-wheel mechanical brakes, which, while marginal at best, were a huge improvement over the Model T. The aftermarket was flooded with Model A speed equipment, so it was the perfect foundation for an adrenaline junkie on a budget."},
      {"para_id":"4", "para":"The Speedster presented here features a highly modified 1932 Ford flathead four-cylinder powerplant, commonly known as a “Model B” engine. Being at least 400 pounds lighter and with twice the horsepower of an original Model A, it is perfectly capable of keeping up with modern highway traffic."},
      {"para_id":"5", "para":"On loan from Dick Moore"}]
  },
  {"id":"NEWCAR2",
  "photo":require('./assets/cars-clipped/50-rocket88.png'),
  "year":"1950", 
  "make":"Oldsmobile", 
  "model":"Rocket 88",
  "engine":"303ci OHV V8",
  "horsepower":"135",
  "fuelDelivery":"2-Barrel Carburetor", 
  "transmission":"Hydra-Matic", 
  "brakes":"4-Wheel Hydraulic Drum", 
  "color":"Black", 
  "interior":"Custom Tuck 'n Roll", 
  "options":"Radio, Heater, Clock, Fender Skirts, Automatic Transmission",
  "production":"10,772", 
  "price":"$1,820",
  "gallery":[
      require('./assets/50-rocket88/1.jpg'),
      require('./assets/50-rocket88/2.jpg'),
      require('./assets/50-rocket88/3.jpg'),
      require('./assets/50-rocket88/4.jpg'),
      require('./assets/50-rocket88/5.jpg'),
      require('./assets/50-rocket88/6.jpg'),
      require('./assets/50-rocket88/7.jpg'),
      require('./assets/50-rocket88/8.jpg'),
      require('./assets/50-rocket88/9.jpg'),
  ],
  "story":[
     {"para_id":"1", "para":"It’s not surprising that there’s a natural link between the beginnings of rock & roll music and the 1950s automobile — both symbolized the soundtrack of new-found freedoms of American youth, and both genres were considered dangerous for the times."}, 
     {"para_id":"2", "para":"It’s only fitting that Ike Turner’s 1951 recording of “Rocket 88,” which is considered to be the milestone where rhythm & blues became rock & roll, be centered around an automobile, or more specifically an automobile engine, the Oldsmobile Rocket V8. Introduced in 1949, this powerplant was one of the first and most powerful overhead valve V8s found in American autos in the early 1950s. It was the tire-burning terror of drag racing, NASCAR, and thousands of impromptu street races. Oldsmobile adopted the “Rocket” logo in 1950 and continued its use on high performance V8s through the 1970s."},
     {"para_id":"3", "para":"The 1950 “Futuramic” Oldsmobile 88 Coupe on display here is the only non-original vehicle at the museum. It’s decked out with typical 1950s modifications like dual exhaust, lowered suspension, dechromed hood (“nosed”), trunk lid (“decked”), and a tuck ‘n rolled interior — the perfect 50s rock & roll cruiser. In fact, it might be just rock & roll enough to inspire a song..."},
     {"para_id":"4", "para":"On loan from the Burgin and Ann Claiborne Collection"}]
 },
 {"id":"NEWCAR3",
 "photo":require('./assets/cars-clipped/53-champion.png'),
 "year":"1953", 
 "make":"Studebaker", 
 "model":"Champion Starlight Coupe",
 "engine":"170ci Flathead 6-Cylinder",
 "horsepower":"85-90",
 "fuelDelivery":"Single-Barrel Carburetor", 
 "transmission":"3-Speed Manual with Overdrive", 
 "brakes":"4-Wheel Hydraulic Drum", 
 "color":"Ivory Mist", 
 "interior":"Loma Grey Cloth", 
 "options":"Overdrive",
 "production":"70,000", 
 "price":"$1,848",
 "gallery":[
     require('./assets/53-champion/1.jpg'),
     require('./assets/53-champion/2.jpg'),
     require('./assets/53-champion/3.jpg'),
     require('./assets/53-champion/4.jpg'),
     require('./assets/53-champion/5.jpg'),
     require('./assets/53-champion/6.jpg'),
     require('./assets/53-champion/7.jpg'),
     require('./assets/53-champion/8.jpg'),
 ],
 "story":[
    {"para_id":"1", "para":"One of the most influential automotive designs of all time, and often deemed an automotive work of art, the 1953-1954 Studebaker Starlight Coupe has a largely unrecognized place in automotive history. Lithe, clean, fluid, and lower by several inches than any other American car built in the 1950s, it was the first mass produced car built in this country that, according to New York’s Museum of Modern Art, “adapted the design characteristics of European automobiles.” An aesthetic triumph, it continues to influence sports car styling even today."}, 
    {"para_id":"2", "para":"Commonly referred to as the “Loewy coupe,” the car was originally conceived as a sports car concept vehicle by industrial designer Bob Bourke, chief of design for Raymond Loewy Associates, a firm already with history in Studebaker design. A last-minute decision by management rushed the car into production, which proved to be part of its undoing."},
    {"para_id":"3", "para":"Studebaker initially envisioned 1953 production to be around 75% sedans and 25% coupes and hardtops. In actuality, the new body style was so well-received that these figures were actually reversed. Build quality suffered as production ramped up to meet demand, and people waiting for months for new cars would finally withdraw their orders. This, combined with Studebaker having the highest production costs in the industry (and a cut-throat price war in 1953 between Ford and General Motors), contributed to the failure of the coupes and hardtops. The spectacular styling implied a promise that couldn’t be delivered."},
    {"para_id":"4", "para":"Studebaker’s “Family Sports Car” was offered in coupe or hardtop form, with both six-cylinder and V8 engines. For years, the Champion’s Flathead-6 had been tops in Mobil’s annual Fuel Economy Run. As a testimony to its design, its basic body shell was used by Studebaker in its Hawk series through 1964."},
    {"para_id":"5", "para":"On loan from the Burgin and Ann Claiborne Collection"}]
},
{"id":"NEWCAR4",
"photo":require('./assets/cars-clipped/67-chevelle.png'),
"year":"1967", 
"make":"Chevrolet", 
"model":"Chevelle",
"engine":"396ci L78 V8",
"horsepower":"375",
"fuelDelivery":"2-Barrel Carburetor", 
"transmission":"4-Speed Manual", 
"brakes":"Hydraulic and Disc Front, Drum Rear", 
"color":"Tuxedo Black", 
"interior":"Red", 
"options":"Super Sport",
"production":"59,685", 
"price":"$3,212",
"gallery":[
    require('./assets/67-chevelle/1.jpg'),
    require('./assets/67-chevelle/2.jpg'),
    require('./assets/67-chevelle/3.jpg'),
    require('./assets/67-chevelle/4.jpg'),
    require('./assets/67-chevelle/5.jpg'),
    require('./assets/67-chevelle/6.jpg'),
    require('./assets/67-chevelle/7.jpg'),
    require('./assets/67-chevelle/8.jpg'),
    require('./assets/67-chevelle/9.jpg'),
    require('./assets/67-chevelle/10.jpg'),
    require('./assets/67-chevelle/11.jpg'),
    require('./assets/67-chevelle/12.jpg'),
    require('./assets/67-chevelle/13.jpg'),
],
"story":[
   {"para_id":"1", "para":"Introduced in 1964 in response to Ford’s “intermediate” Fairlane, the Chevrolet Chevelle was an instant hit, bridging the gap between the compact Chevy II and the full-sized Impala. The Chevelle was offered in two-door hardtops and convertibles, plus four-door sedans, station wagons, and a sport utility pickup, the El Camino. Over 338,000 were sold the first year."}, 
   {"para_id":"2", "para":"With the introduction of the big block 396 in 1965, a limited run of 201 Chevelle SS396 “Z-16” models were produced between mid-March and mid-April, serving as a test bed for a new high-performance model. The introduction of Pontiac’s GTO in 1964 certainly established that a market existed for such an automobile."},
   {"para_id":"3", "para":"The Chevelle SS396 became a series of its own in 1966, featuring a complete restyle of the body, a broad new grille and bumper treatment, curved side windows, a bulging rear fender line, and, for hardtops, a “flying buttress” roofline, with the rear window tucked into the “C” pillar. Three engine options were available for the 396: a base model with 325 horsepower, a 360-horsepower version, and the L78, a solid lifter version conservatively rated at 375 horsepower (probably for insurance purposes) even though the exact same engine was rated at 425 horsepower in the Impala. Independent dyno tests of L78s have shown closer to 450 horsepower."},
   {"para_id":"4", "para":"1967 showed a subtle refinement of the 1966 styling with a new grille and wraparound tail lights. Improved safety features included a collapsible steering column, dual reservoir master cylinder with warning light, and available front disc brakes. More importantly for the enthusiast, low profile “wide oval” tires were available on the SS396. The L78 engine was dropped from the options list at the beginning of the model year, only to return late in production. The 1967 SS396 on display is only one of 612 built that year with this engine option. Its sales brochure claimed, “…what you’ll see inside will probably bring on a severe compulsion to go driving.” Well said."},
   {"para_id":"5", "para":"On loan from Rich Miller"}]
},
{"id":"NEWCAR5",
"photo":require('./assets/cars-clipped/69-camaro.png'),
"year":"1969", 
"make":"Chevrolet", 
"model":"Camaro SS",
"engine":"396ci V8",
"horsepower":"375",
"fuelDelivery":"Holley 4-Barrel Carburetor", 
"transmission":"4-Speed Manual", 
"brakes":"Front Disc, Rear Drum", 
"color":"Tuxedo Black", 
"interior":"Black", 
"options":"Super Sport",
"production":"243,085 (13,970 SS 396 models)", 
"price":"$3,100",
"gallery":[
    require('./assets/69-camaro/1.jpg'),
    require('./assets/69-camaro/2.jpg'),
    require('./assets/69-camaro/3.jpg'),
    require('./assets/69-camaro/4.jpg'),
    require('./assets/69-camaro/5.jpg'),
    require('./assets/69-camaro/6.jpg'),
    require('./assets/69-camaro/7.jpg'),
    require('./assets/69-camaro/8.jpg'),
    require('./assets/69-camaro/9.jpg'),
    require('./assets/69-camaro/10.jpg'),
    require('./assets/69-camaro/11.jpg'),
],
"story":[
   {"para_id":"1", "para":"Let’s give credit where credit is due — if not for the success of Ford’s Mustang, the Chevrolet Camaro, Dodge Challenger, and a host of other personal vehicles would likely not exist. Arriving almost three years late to the “pony car” wars, Chevrolet had to quickly play catch up and create a vehicle that was nearly a Corvette at a Corvair price."}, 
   {"para_id":"2", "para":"Based off of Chevrolet’s existing Nova platform and hurried into production, the Camaro was a challenging ask for GM stylists. But they were up to the task and created a clean design that is still considered one of the best looking cars of all time. Available only as a coupe or convertible, the first generation Camaro in 1967-1968 combined lean and muscular looks with few and minor embellishments compared to other high performance cars of the day. But the best was still to come."},
   {"para_id":"3", "para":"The 1969 Camaro carried over the previous year's drivetrain and major mechanical components, but all-new sheet metal, except the hood and trunk lid, gave the car a substantially sportier look. The grille was redesigned with a heavy “V” cant and deeply inset headlights. The rear fenders were pulled out, and character lines trailing the rear wheel openings gave Camaro an aura of speed. Simulated grilles forward of the rear fenders provided accent detail while wide tail lights exaggerated the car’s width. In short, every effort was made to make the 1969 Camaro wider, sleeker, and more muscular without borrowing from any previous designs. It worked, as this body style is considered an automotive landmark. When the Camaro was reintroduced in 2010, its inspiration and many of its styling cues came straight from the 1969 model."},
   {"para_id":"4", "para":"There was plenty of performance to go along with this one-year-only styling as no less than 12 engines were available ranging from an entry level six-cylinder to a fire-breathing big block V8. Numerous option packages, along with almost an unlimited number of performance and trim levels, allowed Chevrolet to blanket Camaro’s end of the personal car market. There was practically a Camaro available for everyone’s taste, but for gear-headed Baby Boomers (and their children and grandchildren), performance versions of the 1969 Camaro are the closest thing to a full-sized Hot Wheels car."},
   {"para_id":"5", "para":"The 1969 Camaro on display here features the performance SS option, including the L78 solid lifter 396 cubic inch power plant. Conservatively rated at 375 horsepower, it is one of 3,823 built with this engine."},
   {"para_id":"6", "para":"On loan from Dr. Robin Campassi"}]
},
{"id":"NEWCAR6",
"photo":require('./assets/cars-clipped/70-challenger.png'),
"year":"1970", 
"make":"Dodge", 
"model":"Challenger R/T",
"engine":"426ci V8 Hemi",
"horsepower":"425",
"fuelDelivery":"Two 4-Barrel Carburetors", 
"transmission":"3-Speed Automatic", 
"brakes":"Front Disc, Rear Drum", 
"color":"Bright Red", 
"interior":"White", 
"options":"Super Track Pak with 426 Hemi Engine",
"production":"76,935 (1 of 12 426 Hemi Convertibles)", 
"price":"$4,768",
"gallery":[
    require('./assets/70-challenger/1.jpg'),
    require('./assets/70-challenger/2.jpg'),
    require('./assets/70-challenger/3.jpg'),
    require('./assets/70-challenger/4.jpg'),
    require('./assets/70-challenger/5.jpg'),
    require('./assets/70-challenger/6.jpg'),
    require('./assets/70-challenger/7.jpg'),
    require('./assets/70-challenger/8.jpg'),
    require('./assets/70-challenger/9.jpg'),
    require('./assets/70-challenger/10.jpg'),
],
"story":[
   {"para_id":"1", "para":"The “pony car” revolution started by Ford’s Mustang in 1964 had fully matured by 1970 when Dodge finally released its new Challenger model. An upscale companion car to Plymouth’s radically redesigned Barracuda, the Challenger was priced to compete against Pontiac’s Firebird and Mercury’s Cougar. Due to a market flooded with performance vehicles and external government regulations, this version of the Challenger never lived up to marketing expectations and only survived four years. Nonetheless, its aggressive looks combined with luxury features make it one of the most sought-after cars of the muscle car era."}, 
   {"para_id":"2", "para":"Challenger had no less than nine engine options in 1970, but for the ultimate in performance and bragging rights, there was only one choice: the NASCAR-derived 426 Hemi, laughingly rated at 425 horsepower to satisfy government and insurance regulations. Actual output was thought to be closer to 475 horsepower. Backed by Chrysler’s almost bulletproof drivetrain, the Hemi’s reputation was legendary both on the track and street. Nothing looked or sounded like it and it became the epitome of a muscle car. There was nothing subtle about a Hemi, and the Challenger was not for the faint of heart."},
   {"para_id":"3", "para":"All this power came with a price, and the Hemi engine’s hefty premium meant few buyers could justify such a vehicle, making any authentic Hemi car a rarity today."},
   {"para_id":"4", "para":"This example is one of the rarest — a 1970 Challenger R/T convertible with a 426 Hemi engine. Convertible versions of the R/T were a one-year-only body style, and convertibles were not available as R/Ts in 1971. They were totally discontinued by 1972. Along with the 426 Hemi engine, this vehicle is equipped with a heavy duty Torqueflite transmission and the Super Track Pak, which includes front disc brakes and a severe duty Dana 60 rear axle."},
   {"para_id":"5", "para":"This 1970 Challenger R/T convertible is one of only 12 produced. Seven were automatics, and five were 4-speeds. Of the 12, nine were sold in the USA, three went to Canada, and one was shipped to Europe. It is a car combining the best styling cues of the early seventies with ultimate horsepower and supreme rarity."},
   {"para_id":"6", "para":"On loan from Hines Racing"}]
},
  {"id":"1",
  "photo":require('./assets/cars-clipped/49-crosley.png'),
  "year":"1949", 
  "make":"Crosley", 
  "model":"Hot Shot",
  "engine":"44.2ci Inline 4-Cylinder",
  "horsepower":"26",
  "fuelDelivery":"Single-Barrel Carburetor", 
  "transmission":"3-Speed Manual", 
  "brakes":"4-Wheel Disc", 
  "color":"Jonquil Yellow", 
  "interior":"Red Leather", 
  "options":"Trimmed windshield",
  "production":"752", 
  "price":"$950",
  "gallery":[
      require('./assets/49-crosley/1.gif'),
      require('./assets/49-crosley/2.jpg'),
      require('./assets/49-crosley/3.jpg'),
      require('./assets/49-crosley/4.jpg'),
      require('./assets/49-crosley/5.jpg'),
      require('./assets/49-crosley/6.jpg'),
      require('./assets/49-crosley/7.jpg'),
      require('./assets/49-crosley/8.jpg'),
      require('./assets/49-crosley/9.jpg'),
  ],
  "story":[
     {"para_id":"1", "para":"Among American sports cars, the Crosley Hot Shot can be considered the first. The engine was remarkable: a single overhead camshaft, a capacity of only 726cc, and a whopping 26 horsepower. It was originally developed as a small sedan, but its sporting capabilities won out by production in 1949 as a two-seat sports car. The Hot Shot wasn’t pretty — it was sometimes called a bathtub on wheels — but it could hit 75 MPH and was rather quick for its specs."}, 
     {"para_id":"2", "para":"The Hot Shot here is race-ready with a trimmed windshield, hand-painted numbers, and all badging removed for track safety. In 1950, this exact car in front of you won the prestigious Twelve Hours of Sebring race by the “index of performance,” achieved by averaging the best speed for its displacement. Hot Shots were raced all over the US until production ceased in 1952, just a few years after its release."},
     {"para_id":"3", "para":"On loan from Bill & Laurie Cunningham"}]
 },
  {"id":"2",
   "photo":require('./assets/cars-clipped/50-mg.png'),
   "year":"1950", 
   "make":"MG", 
   "model":"TD",
   "engine":"1,250cc (1.3 L) XPAG Inline 4-cylinder",
   "horsepower":"57",
   "fuelDelivery":"SU Electric Fuel Pump", 
   "transmission":"4-Speed Manual", 
   "brakes":"Drum", 
   "color":"Old English White (1 of 2)", 
   "interior":"Red Leather", 
   "options":"Wire wheels, Brooklands Steering Wheel, Arnolt Heater",
   "production":"2,495 built in U.K. and exported to U.S.", 
   "price":"$1,850",
   "gallery":[
       require('./assets/50-mg/1.jpg'),
       require('./assets/50-mg/2.jpg'),
       require('./assets/50-mg/3.jpg'),
       require('./assets/50-mg/4.jpg'),
       require('./assets/50-mg/5.jpg'),
       require('./assets/50-mg/6.jpg'),
       require('./assets/50-mg/7.jpg'),
       require('./assets/50-mg/8.jpg'),
       require('./assets/50-mg/9.jpg'),
       require('./assets/50-mg/10.jpg'),     
   ],   
   "story":[
      {"para_id":"1", "para":"This MG is the only non-American vehicle in our exhibit, but it’s just as influential on the American auto as any other car on display. By the late 1940s, Americans were catching sports car fever, and MG knew it. The British-built TD was designed to capture more of the American market as they made the car wider, longer, and heavier than its predecessor, the TC. They even offered a left-hand drive version specifically for the U.S., as seen here."}, 
      {"para_id":"2", "para":"This car, along with other European roadsters like the Jaguar XK120, heavily influenced early American-made sports cars. While stationed abroad during WWII, many Americans fell in love with the small, sleek roadsters built for winding European roads. Many foreign producers noticed the interest in their cars, and began exporting models for the American market. MG produced nearly 30,000 standard TD models, but the car in front of you is one of only about 2,500 TDs built for the U.S. in 1950."},
      {"para_id":"3", "para":"On loan from Hiram Shepard"}]
  },
  {"id":"3",
   "photo":require('./assets/cars-clipped/54-corvette.png'),
   "year":"1954", 
   "make":"Chevrolet", 
   "model":"Corvette",
   "engine":"235ci Inline “Blue-Flame Six“",
   "horsepower":"150",
   "fuelDelivery":" 3 “Side-Draft” Carters", 
   "transmission":"2-Speed Automatic", 
   "brakes":"Drum", 
   "color":"Polo White", 
   "interior":"Red Leather", 
   "options":"None",
   "production":"318 of 3,640", 
   "price":"$3,072",
   "gallery":[
       require('./assets/54-corvette/1.png'),
       require('./assets/54-corvette/2.jpg'),
       require('./assets/54-corvette/3.jpg'),
       require('./assets/54-corvette/4.jpg'),
       require('./assets/54-corvette/5.jpg'),
       require('./assets/54-corvette/6.jpg'),
       require('./assets/54-corvette/7.png'),
       require('./assets/54-corvette/8.jpg'),
       require('./assets/54-corvette/9.jpg'),
       require('./assets/54-corvette/10.jpg'),
       require('./assets/54-corvette/11.jpg'),
       require('./assets/54-corvette/12.jpg'),
       require('./assets/54-corvette/13.jpg'),
       require('./assets/54-corvette/14.jpg'),
       require('./assets/54-corvette/15.jpg'),
       require('./assets/54-corvette/16.jpg'),
       require('./assets/54-corvette/17.jpg'),
       require('./assets/54-corvette/18.jpg'),
       require('./assets/54-corvette/19.jpg'),
       require('./assets/54-corvette/20.jpg'),
       require('./assets/54-corvette/21.jpg'),
       require('./assets/54-corvette/22.jpg'), 
       require('./assets/54-corvette/23.jpg'),       
   ],    
   "story":[
      {"para_id":"1", "para":"As foreign-made cars like the MG TD and the Jaguar XK120 crept into America’s field of view in the late 1940s, U.S. automakers decided to try their hand at building small, svelte roadsters that were as fun to drive as they were to look at. Chevrolet was the first major manufacturer to roll a sports car off the line, and it did so to great fanfare at the company’s 1953 Motorama showcase."}, 
      {"para_id":"2", "para":"Officially released in December of 1953, only 300 were initially made and distributed to select, high-profile individuals. The car you’re looking at is the 318th Corvette built in its first full production year of 1954. Note the sleek fiberglass body with its toothy grille, “jet-pod” tail lamps, and lack of exterior door handles. The car’s design was stunning, but it masked some mechanical quirks and an underpowered engine. Because of this, Chevrolet only sold two-thirds of the initial batch of 1954 models. Later models would be faster and better-built, encouraged by some fierce competition from the Ford Thunderbird."}]
  },
  {"id":"4",
   "photo":require('./assets/cars-clipped/57-thunderbird.png'),
   "year":"1957", 
   "make":"Ford", 
   "model":"Thunderbird",
   "engine":"312ci V-8",
   "horsepower":"245",
   "fuelDelivery":"Holley 4-Barrel Carburetor", 
   "transmission":"3-Speed Automatic (“Ford-O-Matic”)", 
   "brakes":"Drum (modified to Disc)", 
   "color":"Raven Black", 
   "interior":"Black/White Leather", 
   "options":"Porthole Top",
   "production":"21,380", 
   "price":"$3,406", 
   "gallery":[
       require('./assets/57-thunderbird/1.jpg'),
       require('./assets/57-thunderbird/2.jpg'),
       require('./assets/57-thunderbird/3.jpg'),
       require('./assets/57-thunderbird/4.jpg'),
       require('./assets/57-thunderbird/5.jpg'),
       require('./assets/57-thunderbird/6.jpg'),
       require('./assets/57-thunderbird/7.jpg'),
       require('./assets/57-thunderbird/8.jpg'),
       require('./assets/57-thunderbird/9.jpg'),
       require('./assets/57-thunderbird/10.jpg'),
       require('./assets/57-thunderbird/11.jpg'),
       require('./assets/57-thunderbird/12.jpg'),
       require('./assets/57-thunderbird/13.jpg'),
       require('./assets/57-thunderbird/14.jpg'),
       require('./assets/57-thunderbird/15.jpg'),
       require('./assets/57-thunderbird/16.jpg'),      
   ],    
   "story":[
      {"para_id":"1", "para":"First introduced in 1955 as a response to Chevrolet’s new sporty offering, the Thunderbird was fast, well-built, and beautiful. It massively outsold the Corvette, as Ford had learned from some of Chevy’s mistakes. It had glass windows, a sturdy steel frame, and boasted a burly Mercury V8 engine that outpaced the ‘Vette’s sluggish inline 6-cylinder."}, 
      {"para_id":"2", "para":"While 1955 and 1956 models were fairly similar, Ford reimagined the Thunderbird for 1957, the model you see here. With a new grille, restyled bumpers, larger tail lights, and a redesigned dashboard, the ‘57 T-bird improved on an already staggering success of a car. Many regard the 1957 Thunderbird as the best version of the car Ford ever made. It’s also considered to be the last true Thunderbird, as the company only produced larger, four-seat versions of the car in 1958 and beyond. But Ford had proven that a two-seater could be a commercial success."}, 
      {"para_id":"3", "para":"On loan from the Vining family"}]
  },
  {"id":"5",
  "photo":require('./assets/cars-clipped/59-corvette.png'),
  "year":"1959", 
  "make":"Chevrolet", 
  "model":"Corvette",
  "engine":"283ci V8",
  "horsepower":"270",
  "fuelDelivery":"Two Carter 4-Barrel Carburetors (“Dual-Quad”)", 
  "transmission":"4-Speed Manual with T-Shifter", 
  "brakes":"Drum", 
  "color":"Inca Silver with White Coves", 
  "interior":"Black Leather", 
  "options":"None",
  "production":"8,825 of 9,670", 
  "price":"$4,017",
  "gallery":[
       require('./assets/59-corvette/1.jpg'),
       require('./assets/59-corvette/2.jpg'),
       require('./assets/59-corvette/3.jpg'),
       require('./assets/59-corvette/4.jpg'),
       require('./assets/59-corvette/5.jpg'),
       require('./assets/59-corvette/6.jpg'),
       require('./assets/59-corvette/7.jpg'),
       require('./assets/59-corvette/8.jpg'),
       require('./assets/59-corvette/9.jpg'),
       require('./assets/59-corvette/10.jpg'),
       require('./assets/59-corvette/11.jpg'),
       require('./assets/59-corvette/12.jpg'),      
       require('./assets/59-corvette/13.jpg'),
   ],  
  "story":[
     {"para_id":"1", "para":"Though Ford had proven it had a stronger public appeal with the Thunderbird, by 1958 it strayed from its sports car roots and became more of a personal luxury vehicle. Chevrolet, on the other hand, only dug in deeper with third redesign of the Corvette. They were committed to building America’s only true sports car."}, 
     {"para_id":"2", "para":"Some claimed the 1958 Corvette was “over-designed” with too much chrome and exaggerated styling (possibly an overreaction to the Thunderbird). Chevrolet would address this issue in the 1959 model you see here by removing some of the excessive glitz like washboard ridges on the hood and chrome “tusks” that ran down the trunk. The car also now had a proper overhead V8 (introduced in 1956), giving it real race-ready power and a top speed of 128 MPH."}]
  },
  {"id":"6",
  "photo":require('./assets/cars-clipped/63-avanti.png'),
  "year":"1963", 
  "make":"Studebaker", 
  "model":"Avanti",
  "engine":"289ci V8",
  "horsepower":"240",
  "fuelDelivery":"4-Barrel Carburetor", 
  "transmission":"3-Speed Automatic", 
  "brakes":"Disc", 
  "color":"Avanti White", 
  "interior":"Black Leather", 
  "options":"None",
  "production":"4,643", 
  "price":"$4,445",
   "gallery":[
       require('./assets/63-avanti/1.jpg'),
       require('./assets/63-avanti/2.jpg'),
       require('./assets/63-avanti/3.jpg'),
       require('./assets/63-avanti/4.jpg'),
       require('./assets/63-avanti/5.jpg'),
       require('./assets/63-avanti/6.jpg'),
       require('./assets/63-avanti/7.jpg'),
       require('./assets/63-avanti/8.jpg'),
       require('./assets/63-avanti/9.jpg'),
       require('./assets/63-avanti/10.jpg'),
       require('./assets/63-avanti/11.jpg'),
       require('./assets/63-avanti/12.jpg'),
       require('./assets/63-avanti/13.jpg'),
       require('./assets/63-avanti/14.jpg'),
       require('./assets/63-avanti/15.jpg'),
       require('./assets/63-avanti/16.jpg'),
       require('./assets/63-avanti/17.jpg'),
       require('./assets/63-avanti/18.jpg'),
       require('./assets/63-avanti/19.jpg'),        
   ],   
  "story":[
     {"para_id":"1", "para":"The Avanti was supposed to save Studebaker. Unique styling, a powerful engine, and an aircraft-inspired interior aimed to reverse the company’s recent rapid decline in sales. They unveiled a prototype of the car in 1962, but stumbled over production problems for more than a year. The car was selected to pace the 1962 Indy-500 but it wasn’t ready in time and Studebaker lost out on a major promotional push for the Avanti. The car’s eventual release in 1963 came too late to save the company. The plant that built the Avanti was closed in December of 1963, and Studebaker would build its last car less than three years later."}, 
     {"para_id":"2", "para":"The Avanti was influential, nonetheless. Notice the rear seat belts, a novel addition at the time. Studebaker began installing seat belts on all their cars in March of 1963, and were one of the first American automakers to blend safety and style. Other safety innovations include a fully integral roll cage, door safety latches, and a fully protected fuel tank. It also offered disc brakes as standard equipment. Other companies began following suit and seat belts, along with head rests and other safety measures, were mandated by law in 1968."}, 
     {"para_id":"3", "para":"On loan from the Burgin and Ann Claiborne Collection"}]
  },
  {"id":"7",
  "photo":require('./assets/cars-clipped/64-dart.png'),
  "year":"1964", 
  "make":"Dodge", 
  "model":"Dart GT",
  "engine":"273ci V8 Chrysler LA Series",
  "horsepower":"180",
  "fuelDelivery":"2-Barrel Carburetor", 
  "transmission":"3-Speed TorqueFlite Push-Button Automatic", 
  "brakes":"Drum", 
  "color":"Roman Dark Red", 
  "interior":"Black", 
  "options":"None",
  "production":"50,700", 
  "price":"$2,600", 
   "gallery":[
       require('./assets/64-dart/1.jpg'),
       require('./assets/64-dart/2.jpg'),
       require('./assets/64-dart/3.jpg'),
       require('./assets/64-dart/4.jpg'),
       require('./assets/64-dart/5.jpg'),
       require('./assets/64-dart/6.jpg'),
       require('./assets/64-dart/7.jpg'),
       require('./assets/64-dart/8.jpg'),
       require('./assets/64-dart/9.jpg'),
       require('./assets/64-dart/10.jpg'),
       require('./assets/64-dart/11.jpg'),
       require('./assets/64-dart/12.jpg'),
       require('./assets/64-dart/13.jpg'),      
   ],     
  "story":[
     {"para_id":"1", "para":"The Dart was a massively popular car for Dodge in the 1960s — almost too popular. At the beginning of the decade, Dart models made up 87% of the company’s sales. But that didn’t seem to phase Dodge. By 1964, the Dart was available in four different styles: convertible, sedan, station wagon, and hard-top coupe. While many were built with Chrysler’s standard Slant-Six engine, Dodge introduced a compact, lightweight 273ci V8 engine specifically for the GT coupe and convertible, with which the model you see here is equipped."}, 
     {"para_id":"2", "para":"A truly unique feature of the 1964 Dart is its push-button automatic transmission (see image in gallery). To shift, the driver plunges a cylindrical button into the dashboard to the left of the steering wheel, which would redirect the transmission’s fluid path. The system (which lacked a “Park” button in favor of a lever located beside the push-buttons) proved to be more of a hurdle than a convenience and 1964 was the last year Dodge implemented push-button transmission. Legend has it, however, that left-handed saxophone players everywhere love to drive and shift this car!"}, 
     {"para_id":"3", "para":"On loan from Rob Whitlow"}]
  },
  {"id":"8",
  "photo":require('./assets/cars-clipped/64-5-mustang.png'),
  "year":"1964.5", 
  "make":"Ford", 
  "model":"Mustang",
  "engine":"289ci V8",
  "horsepower":"225",
  "fuelDelivery":"4-Barrel Carburetor", 
  "transmission":"3-Speed Manual", 
  "brakes":"Drum", 
  "color":"Rangoon Red", 
  "interior":"Red Parchment Vinyl", 
  "options":"Power Top",
  "production":"680,000", 
  "price":"$2,368",
   "gallery":[
       require('./assets/64-5-mustang/1.jpg'),
       require('./assets/64-5-mustang/2.jpg'),
       require('./assets/64-5-mustang/3.jpg'),
       require('./assets/64-5-mustang/4.jpg'),
       require('./assets/64-5-mustang/5.jpg'),
       require('./assets/64-5-mustang/6.jpg'),
       require('./assets/64-5-mustang/7.jpg'),
       require('./assets/64-5-mustang/8.jpg'),
       require('./assets/64-5-mustang/9.jpg'),
       require('./assets/64-5-mustang/10.jpg'),
       require('./assets/64-5-mustang/11.jpg'),
       require('./assets/64-5-mustang/12.jpg'),
       require('./assets/64-5-mustang/13.jpg'),
       require('./assets/64-5-mustang/14.jpg'),
       require('./assets/64-5-mustang/15.jpg'),
       require('./assets/64-5-mustang/16.jpg'),
       require('./assets/64-5-mustang/17.jpg'),
       require('./assets/64-5-mustang/18.jpg'),        
   ], 
  "story":[
     {"para_id":"1", "para":"Introduced in the spring of 1964 (and subsequently dubbed the “1964.5”), the first-ever Ford Mustang broke records with more than 680,000 sold in its 18-month inaugural model year. The car was fast, fun, and affordable. Storied Ford executive Lee Iacocca had done his homework and hit the demographic nail on the head when he set out to build a “youthful” sports car."}, 
     {"para_id":"2", "para":"Since Ford was targeting a younger buyer with the Mustang, the car had to be relatively inexpensive. Developing it from scratch would have pushed the project beyond the desired profitability mark, so Iacocca repurposed the chassis and many parts from the existing (and dreary) Ford Falcon. (In fact, Car and Driver famously called the Falcon “a piece of machinery about as exciting as a dish of baby food.”) "}, 
     {"para_id":"3", "para":"Like Iacocca himself, the Mustang has since become an American automotive icon, and remains one of the best bang-for-your-buck sports cars on the market. It was so popular upon its release that it created a new sub-market of sports cars: the Pony Car."}]
  },
  {"id":"9",
  "photo":require('./assets/cars-clipped/67-corvette.png'),
  "year":"1967", 
  "make":"Chevrolet", 
  "model":"Corvette Stingray",
  "engine":"427ci V8",
  "horsepower":"435",
  "fuelDelivery":"Three Holley 2-Barrel Carburetors (“Tri-Power”)", 
  "transmission":"4-Speed Manual with T-Shifter", 
  "brakes":"Disc", 
  "color":"Rally Red", 
  "interior":"Black Leather", 
  "options":"Side Exhaust (installed by a left-handed mechanic — ask the staff!)",
  "production":"22,940 (8,504 coupes)", 
  "price":"$4,388",
   "gallery":[
       require('./assets/67-corvette/1.jpg'),
       require('./assets/67-corvette/2.jpg'),
       require('./assets/67-corvette/3.jpg'),
       require('./assets/67-corvette/4.jpg'),
       require('./assets/67-corvette/5.jpg'),
       require('./assets/67-corvette/6.jpg'),
       require('./assets/67-corvette/7.jpg'),
       require('./assets/67-corvette/8.jpg'),
       require('./assets/67-corvette/9.jpg'),
       require('./assets/67-corvette/10.jpg'),
       require('./assets/67-corvette/11.jpg'),
       require('./assets/67-corvette/12.jpg'),
       require('./assets/67-corvette/13.jpg'),
       require('./assets/67-corvette/14.jpg'),
       require('./assets/67-corvette/15.jpg'),
       require('./assets/67-corvette/16.jpg'),      
   ],  
  "story":[
     {"para_id":"1", "para":"The 1967 Corvette Sting Ray was the last Corvette of the second generation (“C2”). Five years of refinements made it the best of the C2 line, and quite possibly the best Corvette ever built. The car was phenomenal, lauded for its handling, road adhesion, and sheer power. Dubbed the Sting Ray (and ever since 1968, “Stingray”), the name calls attention to the lines of the car that come to a point on both the hood and the trunk."}, 
     {"para_id":"2", "para":"Because Chevy would completely redesign the Corvette the following year, the changes to the 1967 were minimal: restyled fender vents, less ornamentation, and a lower, less chunky appearance. There was also now a single backup light, mounted above the license plate. Even though these design updates made for a better car, many buyers knew a fully revamped Corvette was coming their way, and sales dipped in 1967 by nearly 20% — making this Corvette one of the rarer models of the era."}, 
     {"para_id":"3", "para":"The vehicle in front of you is Bloomington Gold certified achieving a score of 99.3."}]
  },
  {"id":"10",
  "photo":require('./assets/cars-clipped/67-shelby.png'),
  "year":"1967", 
  "make":"Shelby", 
  "model":"GT500",
  "engine":"427cu V8 “Side Oiler” (1 of only 6 built)",
  "horsepower":"485",
  "fuelDelivery":"Two Holley 4-Barrel Barburetors", 
  "transmission":"C6 “Police Special” Automatic", 
  "brakes":"Power Disc", 
  "color":"Brittany Blue Metallic", 
  "interior":"White", 
  "options":"Autographed and driven by Carroll Shelby as part of his race team",
  "production":"2,048", 
  "price":"$4,195", 
   "gallery":[
       require('./assets/67-shelby/1.jpg'),
       require('./assets/67-shelby/2.jpg'),
       require('./assets/67-shelby/3.jpg'),
       require('./assets/67-shelby/4.jpg'),
       require('./assets/67-shelby/5.jpg'),
       require('./assets/67-shelby/6.jpg'),
       require('./assets/67-shelby/7.jpg'),
       require('./assets/67-shelby/8.jpg'),
       require('./assets/67-shelby/9.jpg'),
       require('./assets/67-shelby/10.jpg'),
       require('./assets/67-shelby/11.jpg'),
       require('./assets/67-shelby/12.jpg'),
       require('./assets/67-shelby/13.jpg'),       
       
   ],   
  "story":[
     {"para_id":"1", "para":"Carroll Shelby was a flight instructor in World War II before entering the world of car racing as a driver. After retiring from racing due to health problems, Shelby partnered with Ford to start creating performance versions of their cars through his company, Shelby American. The first Shelby-built vehicles appeared in 1965, but the Mustang variants really started to shine in 1967."}, 
     {"para_id":"2", "para":"Built with the same engine Shelby’s racing team used to claim the top three places in the 1966 24 Hours of Le Mans race, this 1967 Shelby GT500 was the most powerful Mustang to-date. It blended sheer brute force with true racing-inspired design. The fiberglass hood sports a functional air scoop and the trunk lid joins seamlessly with the tailpiece to form a spoiler lip. When reflecting on the 1967 GT500, Carroll Shelby said, “This is the first car I’m really proud of.” Coincidentally, it would be the last Shelby Mustang actually built at a Shelby American factory. Ford continued to work with Shelby, but they consolidated production in 1968 and beyond."}, 
     {"para_id":"3", "para":"On loan from Cofer’s Classics"}]
  },
  {"id":"11",
  "photo":require('./assets/cars-clipped/69-corvette.png'),
  "year":"1969", 
  "make":"Chevrolet", 
  "model":"Corvette Stingray",
  "engine":"427ci V8",
  "horsepower":"435",
  "fuelDelivery":"Three Holley 2-Barrel Carburetors (“Tri-Power”)", 
  "transmission":"4-Speed Manual with T-Shifter", 
  "brakes":"Drum", 
  "color":"Riverside Gold", 
  "interior":"Black Leather", 
  "options":"Side Mount Exhaust",
  "production":"38,762", 
  "price":"$6,189", 
   "gallery":[
       require('./assets/69-corvette/1.jpg'),
       require('./assets/69-corvette/2.jpg'),
       require('./assets/69-corvette/3.jpg'),
       require('./assets/69-corvette/4.jpg'),
       require('./assets/69-corvette/5.jpg'),
       require('./assets/69-corvette/6.jpg'),
       require('./assets/69-corvette/7.jpg'),
       require('./assets/69-corvette/8.jpg'),
       require('./assets/69-corvette/9.jpg'),
       require('./assets/69-corvette/10.jpg'),
       require('./assets/69-corvette/11.jpg'),
       require('./assets/69-corvette/12.jpg'),
       require('./assets/69-corvette/13.jpg'),
       require('./assets/69-corvette/14.jpg'),
       require('./assets/69-corvette/15.jpg'),
       require('./assets/69-corvette/16.jpg'),     
   ],  
  "story":[
     {"para_id":"1", "para":"By 1968, the Corvette had entered a new era, noted most by a dramatic change in styling. The “C3” generation cars had a lower stance, higher fenders, and an overall more extreme look. The “Stingray” designation had also returned after a year absent (and no longer “Sting Ray” as seen on the 1967 model)."}, 
     {"para_id":"2", "para":"Perhaps most notably, the hard-top coupes were also now equipped with a T-top, added in part for rigidity. Without it, and when equipped with the powerful 427ci V8 option, the car would twist its own chassis under strain from the massive amounts of torque the engine was capable of. About this C3 Corvette, Car and Driver magazine wrote, “The small-engine Corvettes are marginally faster and extraordinarily civilized. The large-engine Corvettes are extraordinarily fast and marginally civilized.” We agree."}]
  },
  {"id":"12",
  "photo":require('./assets/cars-clipped/70-mustang.png'),
  "year":"1970", 
  "make":"Ford", 
  "model":"Mustang BOSS 302",
  "engine":"302ci V8",
  "horsepower":"290",
  "fuelDelivery":"Two Holley 4-Barrel Carburetors", 
  "transmission":"Toploader 4-Speed Manual", 
  "brakes":"Front Disc, Rear Drum", 
  "color":"Calypso Coral, Black Jade", 
  "interior":"Black", 
  "options":"“Drag Pack” Package, Shaker Hood",
  "production":"198,239 (7,013 BOSS 302 models)", 
  "price":"$3,325",
   "gallery":[
       require('./assets/70-mustang/1.jpg'),
       require('./assets/70-mustang/2.jpg'),
       require('./assets/70-mustang/3.jpg'),
       require('./assets/70-mustang/4.jpg'),
       require('./assets/70-mustang/5.jpg'),
       require('./assets/70-mustang/6.jpg'),
       require('./assets/70-mustang/7.jpg'),
       require('./assets/70-mustang/8.jpg'),
       require('./assets/70-mustang/9.jpg'),
       require('./assets/70-mustang/10.jpg'),
       require('./assets/70-mustang/11.jpg'),   
   ],     
  "story":[
     {"para_id":"1", "para":"In early 1968, Semon “Bunkie” Knudsen, who had come from Pontiac where he helped create the Trans-Am, defected from GM to become president of Ford. He brought with him stylist Larry Shinoda, who led the 1968 redesign of the Corvette. Together, they aimed to take the Mustang from Pony Car to muscle car, and they started with the BOSS 302."}, 
     {"para_id":"2", "para":"Like he had at Pontiac, Knudsen wanted to pack the Mustang full of as much power as possible. So Shinoda designed a 1969 Mustang variant around a lightweight 302 cubic-inch engine — because it’s what the boss wanted. Ford built 1,628 BOSS 302s in 1969, and more than quadrupled production in 1970. Knudsen would last less than two years at Ford, and so would the BOSS 302. This 1970 was the last model produced of the performance-forward Mustang. The car in front of you sports a unique upgrade: a factory hood-mounted tachometer."}, 
     {"para_id":"3", "para":"On loan from Cofer’s Classics"}]
  },

];